CRUD2/Controllers/AjaxCrudController.cs
using CRUD2.ActionFilters;
using CRUD2.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace CRUD2.Controllers
{
    [LogActionFilter]
    public class AjaxCrudController : Controller
    {
        private ShraddhaEntities7 _dbContext;

        public AjaxCrudController()
        {
            _dbContext = new ShraddhaEntities7();
        }
        public ActionResult Index()
        {
            var users = _dbContext.users.ToList();
            return View(users);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(user u, HttpPostedFileBase imageFile, HttpPostedFileBase resumeFile)
        {
            if (ModelState.IsValid)
            {
                u.profile_photo = SaveUploadedFile(imageFile, "~/Content/img/");
                if(u.profile_photo == null)
                {
                    u.profile_photo = "~/Content/img/dummy_profile_img.png";
                }

                u.resume = SaveUploadedFile(resumeFile, "~/Content/TextFiles/");

                _dbContext.users.Add(u);
                _dbContext.SaveChanges();

                return Json(new { success = true, redirectToUrl = Url.Action("Index") }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                var errors = ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage);
                return Json(new { success = false, message = "Validation failed", errors = errors }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult Edit(int id)
        {
            if (ModelState.IsValid)
            {
                var rowData = _dbContext.users.Where(x => x.userId == id).FirstOrDefault();
                if (rowData != null)
                {
                    TempData["UserId"] = id;
                    TempData.Keep();
                    return View(rowData);
                }
                return HttpNotFound();
            }
            else
            {
                return View();
            }
        }

        [HttpPost]
        public ActionResult Edit(user u, HttpPostedFileBase imageFile, HttpPostedFileBase resumeFile)
        {
            if (ModelState.IsValid)
            {
                var userId = (int)TempData["UserId"];
                var userObj = _dbContext.users.FirstOrDefault(x => x.userId == userId);

                if (userObj != null)
                {
                    userObj.name = u.name;
                    userObj.dob = u.dob;
                    userObj.gender = u.gender;
                    userObj.email = u.email;
                    userObj.address = u.address;
                    userObj.city = u.city;

                    if (imageFile != null && imageFile.ContentLength > 0)
                    {
                        DeleteImageFile(userId);

                        var fileName = Path.GetFileNameWithoutExtension(imageFile.FileName);
                        string extension = Path.GetExtension(imageFile.FileName);
                        fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                        userObj.profile_photo = "~/Content/img/" + fileName;
                        fileName = Path.Combine(Server.MapPath("~/Content/img"), fileName);
                        imageFile.SaveAs(fileName);
                    }

                    if (resumeFile != null && resumeFile.ContentLength > 0)
                    {
                        DeleteTextFile(userId);

                        var fileName = Path.GetFileNameWithoutExtension(resumeFile.FileName);
                        string extension = Path.GetExtension(resumeFile.FileName);
                        fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                        userObj.resume = "~/Content/TextFiles/" + fileName;
                        fileName = Path.Combine(Server.MapPath("~/Content/TextFiles"), fileName);
                        resumeFile.SaveAs(fileName);
                    }

                    _dbContext.Entry(userObj).State = EntityState.Modified;
                    _dbContext.SaveChanges();
                }
                return RedirectToAction("Index");
            }
            else
            {
                return View(u);
            }
        }

        public ActionResult Delete(int id)
        {
            var user = _dbContext.users.Find(id);

            if (user != null)
            {
                DeleteImageFile(id);
                DeleteTextFile(id);
                _dbContext.users.Remove(user);
                _dbContext.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        public void DeleteImageFile(int id)
        {
            var userObj = _dbContext.users.FirstOrDefault(x => x.userId == id);

            var oldImageFilePath = userObj.profile_photo;
            oldImageFilePath = Server.MapPath(oldImageFilePath);
            System.IO.File.Delete(oldImageFilePath);
        }

        public void DeleteTextFile(int id)
        {
            var userObj = _dbContext.users.FirstOrDefault(x => x.userId == id);

            var oldTextFilePath = userObj.resume;
            oldTextFilePath = Server.MapPath(oldTextFilePath);
            System.IO.File.Delete(oldTextFilePath);
        }

        private string SaveUploadedFile(HttpPostedFileBase file, string folderPath)
        {
            if (file != null && file.ContentLength > 0)
            {
                var fileName = Path.GetFileNameWithoutExtension(file.FileName);
                string extension = Path.GetExtension(file.FileName);
                fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                var filePath = Path.Combine(Server.MapPath(folderPath), fileName);
                file.SaveAs(filePath);
                return folderPath + fileName;
            }
            return null;
        }
    }
}

CRUD2/Views/AjaxCrud/Create.cshtml
@model CRUD2.Models.user

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm(Html.BeginForm("Create", "AjaxCrud", FormMethod.Post, new { enctype = "multipart/form-data", id = "create-form" })))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group text-center">
            <input type="file" class="form-control" name="imageFile" id="fileInput" style="display: none;" required onchange="updateImage(this);" />
            <img id="previewImage" class="rounded-circle border-1" src="~/Content/img/dummy_profile_img.png" alt="Profile Photo" style="width: 70px; height: 70px; cursor: pointer;" onclick="document.getElementById('fileInput').click();" />
            <label for="fileInput" style="position: absolute; top: 0; left: 0; width: 50px; height: 50px; cursor: pointer; background-color: rgba(255, 255, 255, 0);"></label>
            @Html.ValidationMessageFor(model => model.profile_photo, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2 mt-2" })
            @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter Your Name" } })
            @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.Label("Gender", htmlAttributes: new { @class = "control-label mt-2" })<br />
            Male:
            @Html.RadioButton("gender", "false", htmlAttributes: new { @class = "me-2" })
            Female:
            @Html.RadioButton("gender", "true")
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dob, htmlAttributes: new { @class = "control-label col-md-2 mt-2" })
            @Html.TextBoxFor(model => model.dob, "{0:yyyy-MM-dd}", new { @class = "form-control", type = "date" })
            @Html.ValidationMessageFor(model => model.dob, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.Label("Email", htmlAttributes: new { @class = "control-label mt-2" })<br />
            @Html.TextBoxFor(model => model.email, new { @class = "form-control", type = "email", placeholder = "Enter your email" })
            @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
        </div>

        <div class="form-group my-2">
            @Html.Label("Hobbies", htmlAttributes: new { @class = "control-label col-md-2 mt-2" })<br />

            <label>Cricket</label>
            @Html.CheckBox("SelectedHobbies", new { value = "Cricket", @class = "me-1" })

            <label>Dancing</label>
            @Html.CheckBox("SelectedHobbies", new { value = "Dancing", @class = "me-1" })

            <label>Reading</label>
            @Html.CheckBox("SelectedHobbies", new { value = "Reading", @class = "me-1" })
        </div>

        <div>
            @Html.Label("City", htmlAttributes: new { @class = "control-label col-md-2 mt-2" })<br />
            @Html.DropDownListFor(m => m.city, new SelectList(Enum.GetValues(typeof(CRUD2.Models.City))), new { @class = "form-control" })
        </div>

        <div>
            @Html.Label("Address", htmlAttributes: new { @class = "control-label mt-2" }) <br />
            @Html.TextAreaFor(model => model.address, new { @class = "form-control", cols = "50", rows = "1" })
            @Html.ValidationMessageFor(model => model.address, "", new { @class = "text-danger" })
        </div>

        <div>
            @Html.LabelFor(model => model.resume, new { @class = "control-label col-md-2 " })
            <input type="file" class="form-control" name="resumeFile" required />
            @Html.ValidationMessageFor(model => model.resume, "", new { @class = "text-danger" })
        </div>

        <div class="form-group text-center">
            <div class="col-md-offset-2 col-md-10 mt-3">
                <input type="submit" value="Create" class="btn btn-lg border-2 rounded-2 btn-success" />
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        $(function () {
            $('#create-form').submit(function (e) {
                e.preventDefault();
                var formData = new FormData($(this)[0]);

                $.ajax({
                    url: '@Url.Action("Create", "AjaxCrud")',
                    type: 'POST',
                    data: formData,
                    dataType: 'json',
                    contentType: false,
                    processData: false,
                    success: function (result) {
                        if (result.success) {
                            window.location.href = result.redirectToUrl;
                        } else {
                            console.error(result.errors);
                        }
                    },
                    error: function (xhr, status, error) {
                        console.error(xhr.responseText);
                    }
                });
            });
        });

        function updateImage(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    document.getElementById('previewImage').setAttribute('src', e.target.result);
                }

                reader.readAsDataURL(input.files[0]);
            }
        }
    </script>
}

CRUD2/Views/AjaxCrud/Edit.cshtml
@model CRUD2.Models.user

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form method="POST" action="@Url.Action("Edit", "AjaxCrud")" id="edit-form" class="shadow-lg m-4 p-4 w-25 d-flex justify-content-center" enctype="multipart/form-data">

    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.userId)
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group text-center">
            <input type="file" class="form-control" name="imageFile" id="fileInput" style="display: none;" required onchange="updateImage(this);" />
            <img id="previewImage" class="rounded-circle border-1" src="@Url.Content(Model.profile_photo)" alt="Profile Photo" style="width: 70px; height: 70px; cursor: pointer;" onclick="document.getElementById('fileInput').click();" />
            <label for="fileInput" style="position: absolute; top: 0; left: 0; width: 50px; height: 50px; cursor: pointer; background-color: rgba(255, 255, 255, 0);"></label>
            @Html.ValidationMessageFor(model => model.profile_photo, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2 mt-2" })
            @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter Your Name" } })
            @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.Label("Gender", htmlAttributes: new { @class = "control-label mt-2" })<br />
            Male:
            @Html.RadioButton("gender", "false", htmlAttributes: new { @class = "me-2" })
            Female:
            @Html.RadioButton("gender", "true")
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dob, htmlAttributes: new { @class = "control-label col-md-2 mt-2" })
            @Html.TextBoxFor(model => model.dob, "{0:yyyy-MM-dd}", new { @class = "form-control", type = "date" })
            @Html.ValidationMessageFor(model => model.dob, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.Label("Email", htmlAttributes: new { @class = "control-label mt-2" })<br />
            @Html.TextBoxFor(model => model.email, new { @class = "form-control", type = "email", placeholder = "Enter your email" })
            @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
        </div>

        <div class="form-group my-2">
            @Html.Label("Hobbies", htmlAttributes: new { @class = "control-label col-md-2 mt-2" })<br />

            <label>Cricket</label>
            @Html.CheckBox("SelectedHobbies", new { value = "Cricket", @class = "me-1" })

            <label>Dancing</label>
            @Html.CheckBox("SelectedHobbies", new { value = "Dancing", @class = "me-1" })

            <label>Reading</label>
            @Html.CheckBox("SelectedHobbies", new { value = "Reading", @class = "me-1" })
        </div>

        <div>
            @Html.Label("City", htmlAttributes: new { @class = "control-label col-md-2 mt-2" })<br />
            @Html.DropDownListFor(m => m.city, new SelectList(Enum.GetValues(typeof(CRUD2.Models.City))), new { @class = "form-control" })
        </div>

        <div>
            @Html.Label("Address", htmlAttributes: new { @class = "control-label mt-2" }) <br />
            @Html.TextAreaFor(model => model.address, new { @class = "form-control", cols = "50", rows = "1" })
            @Html.ValidationMessageFor(model => model.address, "", new { @class = "text-danger" })
        </div>

        <div>
            @Html.LabelFor(model => model.resume, new { @class = "control-label col-md-2 " })
            <input type="file" class="form-control" name="resumeFile" required />
            @Html.ValidationMessageFor(model => model.resume, "", new { @class = "text-danger" })
        </div>

        <div class="form-group text-center">
            <div class="col-md-offset-2 col-md-10 mt-3">
                <input type="submit" value="Edit" class="btn btn-lg border-2 rounded-2 btn-success" />
            </div>
        </div>
    </div>
</form>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script>
        $(function () {
            $('#submitEditForm').click(function (e) {
                e.preventDefault();

                var formData = new FormData($('#edit-form')[0]);

                $.ajax({
                    url: '@Url.Action("Edit", "AjaxCrud")',
                    type: 'POST',
                    data: formData,
                    dataType: 'json',
                    contentType: false,
                    processData: false,
                    success: function (result) {
                        if (result.success) {
                            window.location.href = result.redirectToUrl;
                        } else {
                            console.error(result.errors);
                        }
                    },
                    error: function (xhr, status, error) {
                        console.error(xhr.responseText);
                    }
                });
            });
        });

        function updateImage(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    document.getElementById('previewImage').setAttribute('src', e.target.result);
                }

                reader.readAsDataURL(input.files[0]);
            }
        }
</script>

CRUD2/Views/AjaxCrud/Index.cshtml
@model IEnumerable<CRUD2.Models.user>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    <div class="d-flex float-end mb-3">
        <button class="btn border-4 border-primary"> @Html.ActionLink("Card View", "Index", new { @class = "text-white" })</button>
    </div>

    <div class="table-responsive w-100">
        <table class="table table-hover">
            <tr>
                <th class="text-center">
                    Profile Photo
                </th>
                <th class="text-center">
                    Name
                </th>
                <th class="text-center">
                    Gender
                </th>
                <th class="text-center">
                    Date Of Birth
                </th>
                <th class="text-center">
                    Email
                </th>
                <th class="text-center">
                    Hobbies
                </th>
                <th class="text-center">
                    City
                </th>
                <th class="text-center">
                    Address
                </th>
                <th>
                    Resume Path
                </th>
                <th class="text-center">
                    Edit
                </th>
                <th class="text-center">
                    Delete
                </th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td class="text-center">
                        <img src="@Url.Content(item.profile_photo)" alt="Profile Photo" style="width: 40px; height: 40px;" class="rounded-circle">
                    </td>
                    <td class="text-center">
                        @Html.DisplayFor(modelItem => item.name)
                    </td>
                    <td class="text-center">
                        @if (item.gender == true)
                        {
                            @Html.Raw("Female")
                        }
                        else
                        {
                            @Html.Raw("male")
                        }
                    </td>
                    <td class="text-center">
                        @Html.DisplayFor(modelItem => item.dob)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.email)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.hobbies)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.city)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.address)
                    </td>
                    <td>
                        <a href="@Url.Content(item.resume)">@item.resume</a>
                    </td>
                    <td class="text-center">
                        <button class="btn btn-primary" style="text-decoration: none;">
                            @Html.ActionLink("Edit", "Edit", new { id = item.userId }, new { @class = "btn-link text-white" })
                        </button>
                    </td>
                    <td class="text-center">
                        <button class="btn btn-danger" style="text-decoration: none;">
                            @Html.ActionLink("Delete", "Delete", new { id = item.userId }, new { @class = "btn-link text-white" })
                        </button>
                    </td>
                </tr>
            }

        </table>
    </div>
</div>